repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
      - id: end-of-file-fixer
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
      - id: check-yaml
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
      - id: check-added-large-files
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
      - id: check-json
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
      - id: check-toml
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
      - id: check-merge-conflict
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)

  # Python hooks
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
        args: ['--profile', 'black']

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
        files: st_autocomplete/
        args: [--ignore-missing-imports]

  # JavaScript/TypeScript hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-plugin-react@7.33.2
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-import@2.29.1
          - '@typescript-eslint/eslint-plugin@6.19.1'
          - '@typescript-eslint/parser@6.19.1'
          - typescript@5.3.3
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
        types_or: [javascript, jsx, ts, tsx, css, json, yaml]
        args: [--write]

  # Security checks
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        exclude: ^(examples/|tests/|node_modules/|__tests__/|build/)
        args: [--skip, 'B101', --recursive, st_autocomplete]

ci:
  autofix_commit_msg: 'style: auto fixes from pre-commit hooks'
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
