name: PR - create release version

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'setup.cfg'

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install .[release]

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          registry-url: https://npm.pkg.github.com

      - name: Build the project
        run: bash ./build.sh
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true

      - name: Add built files to git
        run: |
          git add -f st_autocomplete/frontend/build/

      - name: Install semantic release packages
        run: |
          npm install --global --save-dev semantic-release@24 \
          @semantic-release/changelog @semantic-release/commit-analyzer \
          @semantic-release/git @semantic-release/release-notes-generator \
          @semantic-release/github @semantic-release/exec

      - name: Create semantic release
        id: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
