name: PR - Pre-commit Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --user uv
          uv pip install pre-commit
          pre-commit install

      - name: run pre-commit checks
        run: pre-commit run --all-files
